# Generated by Django 4.1.7 on 2023-06-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_postcategory_en_us_postcategory_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='categoryThrough',
        ),
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='postThrough',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_type_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_type_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory_ru',
        ),
        migrations.DeleteModel(
            name='PostCategory_en',
        ),
        migrations.DeleteModel(
            name='PostCategory_ru',
        ),
    ]
