# Generated by Django 4.1.7 on 2023-06-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_postcategory_ru_categorythrough_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_en',
            new_name='text_en_us',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_en',
            new_name='title_en_us',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='Имя категории', max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Имя категории', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Имя категории', max_length=32, null=True, unique=True),
        ),
    ]
