# Generated by Django 4.1.7 on 2023-06-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_category_name_alter_category_name_en_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
    ]
